# Site settings
title: Human Information Interactions
subtitle: "INLS 500-001 (Fall)"
description: "The behavioral and cognitive activities of those who interact with information, with emphasis on the role of information mediators. How information needs are recognized and resolved; use and dissemination of information."
baseurl: ""
url: "https://inls500.johndmart.in"
enforce-ssl: "inls500.johndmart"

mainicon: "/assets/img/500icon.png"

university: University of North Carolina at Chapel Hill
university_url: http://unc.edu
university_logo: "/assets/img/small_blue_300px.png"

unit: School of Information and Library Science
unit_url: http://sils.unc.edu
unit_logo: "/assets/img/ischool-unc_300px.png"

department: INLS
course-number: "500"
course-section: "001"
course-term: Fall
course-year: "2016"
dates: "24 August 2016 - 7 December 2016"
exam: "16 December 2016 (8:00-11:00)"

acknowledgements: 'This syllabus originated with the work of Barbara Wildemuth and Deborah Barreau and has benefitted from the revisions and input of Amelia Gibson, Laura Sheble, Earl Bailey, Ruth Palmquist, Kaitlin Costello, Kathy Brennan, Anita Crescenzi, and others.' 

credits: 'This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a heavily modified version of the <a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> by <a href="http://www.clayharmon.com/">Clay Harmon</a>.'

license: '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png"></a> This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported License</a>.'

# Build settings

future: true

#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "strikethrough", "with_toc_data", "superscript", "autolink"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York

excerpt_separator: <excerpt/>  # you can specify your own separator, of course.

# Set library proxy suffix address
libproxy: libproxy.lib.unc.edu
# Jekyll scholar settings
scholar:
  style: apa.csl
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_data
  bibliography: readings.bib
#  bibliography_template: "{{reference}}" #<abbr>[{{key}}]</abbr>"
  bibliography_template: bibliography-annote-margin
  bibliography_list_tag: ul

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Rake settings
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
#transfer:
# command: rsync
#  settings: -av
#  source: _site/
#  destination: ~/workspace/jdmar3.github.io
  
