# Site settings
title: "INLS 500: Human Information Interaction"
email: john.d.martin.iii@unc.edu
description: "Description"
baseurl: ""
url: "http://inlsjohndmart.in"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
