# Site settings
title: "Human Information Interactions"
tagline: "INLS 500-001 Fall 2015"
author: "John D. Martin III"
author_url: http://johndmart.in
email: john.d.martin.iii@unc.edu
description: "The behavioral and cognitive activities of those who interact with information, with emphasis on the role of information mediators. How information needs are recognized and resolved; use and dissemination of information."
twitter_username: jdmar3
github_username: jdmar3

department: INLS
course-number: "500"
course-section: "001"
course-term: Fall
course-year: "2015"

officehours: "Tu 1230-1430 or by appointment." 
officeloc: "016 Manning Hall (PhDungeon)"

favicon_url: "{{ base.url }}/images/favicon.ico"
university: University of North Carolina at Chapel Hill
university_url: http://unc.edu

unit: School of Information and Library Science
unit_url: http://sils.unc.edu

location: 014 Manning Hall
hours: "1100 - 1215"
days: TuTr
dates: "18 August - 10 December 2015"
exam: 10 December 2015

acknowledgements: 'This syllabus and website originated with the work of Professors Barbara Wildemuth and Deborah Barreau and has benefitted from the revisions and input of Laura Sheble, Earl Bailey, Ruth Palmquist, Kaitlin Costello, Kathy Brennan, Anita Crescenzi and others. Address all comments and questions to <a href="mailto:john.d.martin.iii@unc.edu">John D. Martin III</a>.' 
content_license: 'This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.'

baseurl: ""
url: "http://inlsjohndmart.in"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
