# Site settings
title: Human Information Interactions
subtitle: INLS500-001 (Summer II)
description: "The behavioral and cognitive activities of those who interact with information, with emphasis on the role of information mediators. How information needs are recognized and resolved; use and dissemination of information."

## Comment this section if setting up an archive site ##################
baseurl: ""
url: "https://inls500.johndmart.in"
enforce-ssl: "inls500.johndmart.in"
########################################################################

## Uncomment this section if setting up an archive site ################
#url: "https://ils.unc.edu"
#baseurl: "/courses/2018_summerII/inls500_001"
#enforce-ssl: "ils.unc.edu"
# When mothballed assignments link to statics and there is a GH link
#mothballed: true  
########################################################################

#name: John D. Martin III
#email: john.d.martin.iii@unc.edu
#twitter_username: jdmar3
#github_username:  jdmar3

mainicon: "/assets/img/500icon.png"

department: INLS
course-number: "500"
course-section: "001"
course-term: Summer II
course-year: "2018"
dates: 25 June 2018 - 27 July 2018
exam: 31 July 2017 (15:00-18:00)

acknowledgements: "This syllabus originated with the work of Barbara Wildemuth and Deborah Barreau and has benefitted from the revisions and input of Amelia Gibson, Kaitlin Costello, Anita Crescenzi, and others."

license: 'All content licensed under a <a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.'

license-img: '<a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="CC-BY-NC-SA" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>'

license-img-lrg: '<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="CC-BY-NC-SA" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'

license-summary: 'You may redistribute, remix, or copy content on this site under the same license as above for non-commercial purposes provided that you provide attribution and link back to the source.'

theme-license: '<a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> is &copy; <a href="http://www.clayharmon.com/">Clay Harmon</a> and distributed under the MIT license. This site theme is also distributed under the MIT license.'

credits: 'This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a heavily modified version of the <a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> by <a href="http://www.clayharmon.com/">Clay Harmon</a>.'

# When mothballed, assignments link to assignments/a#.md 
#mothballed: true    

# Build settings

future: true

#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "superscript"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York

excerpt_separator: <excerpt/>  # you can specify your own separator, of course.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  #destination: ~/workspace/jdmar3.github.io